### ISSUE TITLE
importing manifest, does not show up

### ISSUE THREAD

**Issue by bitkarrot** [lnbits/nostr-relay-extension#6]
after importing manifest, extension does not show up. server is restarted, and still does not show up

however importing nostrclient extension is working, as are others. I am using latest commit from lnbits main branch commit f2849a6e68f229bc95cbc038ec0e89ab5aad3cca, March 8, 2023

link used: 
 https://raw.githubusercontent.com/lnbits/nostr-relay-extension/main/manifest.json

<img width="704" alt="Screenshot 2023-03-09 at 5 52 02 PM" src="https://user-images.githubusercontent.com/73979971/224202850-18faddb3-76b2-48a2-94c3-f3e3dbc7d296.png">

<img width="526" alt="Screenshot 2023-03-09 at 5 55 10 PM" src="https://user-images.githubusercontent.com/73979971/224203305-d79e0fba-6621-42d2-95dd-17ad7378afad.png">

**Comment by thibautrey** [comment]
I had the same issue. Looking at the logs it looked like lnbits was hitting a 403 limit reached from github. The solution for me was to simply authenticate by providing an ssh key of lnbits to my github account.

**Comment by motorina0** [comment]
I've just re-tested, works fine: 
https://raw.githubusercontent.com/lnbits/nostr-relay-extension/main/manifest.json
