### ISSUE TITLE
accounts form bug

### ISSUE THREAD

**Issue by bitkarrot** [lnbits/nostr-relay-extension#8]
Hi - not sure if this is a work in progress or if i'm using it incorrectly but for the accounts tab in the relay extension, when i add a npub it doesn't seem to register the data in the table below. 

I am using direct from main branch, and pull from main branch yesterday, April 5, 2023

<img width="658" alt="Screenshot 2023-04-06 at 1 54 21 PM" src="https://user-images.githubusercontent.com/73979971/230492226-6f64987b-945f-47f4-87d3-d3bbdcf0c1d9.png">

**Comment by motorina0** [comment]
hmm, maybe the filter UX is not the best
From the screenshot you are filtering accounts that are both blocked and allowed

**Comment by dharake** [comment]
I have the exact same issue. Adding to whitelist or blacklist is not working. It signals in green below that the account is added, but does not populate in the table. @bitkarrot did you figure out the problem at all?

**Comment by dharake** [comment]
This issue was resolved for me by upgrading from SQLite to Postgres, hope that helps

**Comment by motorina0** [comment]
> Unfortunately, I also see this issue. regardless of toggling allowed or blocked accounts.
> 
> Running LNbits version: 0.10.8, Commit version: 8ed2422ade4fa63eaf51cbcff9a07b85a23cc1f2 using sqllite.

What version of the extension do you use?

**Comment by santyr** [comment]
0.25

**Comment by talvasconcelos** [comment]
Hmm... trying to debug this one!! apparently the CRUD call sends an empty list every time! Although i tested it in SQL and it works!

Needs some more debugging... @motorina0 wouldn't it be better to call them once (from DB) and filter the array client side?
